#App annotation
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#FB Login route
hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /fblogin
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /fbconnect
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /fbconnect
facebook_login:
    pattern: /fblogin/check-facebook    

app_oauth_social:
    pattern: /api/v1/oauth/v2/token/{network}
    defaults: { _controller: AppBundle:Token:getSocialToken, _format:json }
    requirements:
        network:  facebook|google|twitter
        
#Sonata user bundle routing
sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

#sonata_user_admin_resetting:
#    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
#    prefix: /admin/resetting
    
#FOSUserBundle routing   
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#Admin Routing
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

#Api routing
api_routes:
    type: rest
    host: "%api_host_route%"
    resource: "@AppBundle/Resources/config/api_routes.yml"

#Rewritten for prefix /api
fos_oauth_server_token:
  path:     /api/v1/oauth/v2/token
  defaults: { _controller: fos_oauth_server.controller.token:tokenAction }
