utils:
    type:     rest
    prefix:   /api/v1
    resource: AppBundle\Controller\UtilController

users:
    type:     rest
    prefix:   /api/v1
    resource: AppBundle\Controller\UsersController

positions:
    type:     rest
    prefix:   /api/v1
    resource: AppBundle\Controller\PositionsController